### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by sssbling** [0Shino0/share_study_ui#5]
请问这个项目使用了什么区块链技术呢？Hyperledger fabric吗?还是其他的呢？

**Comment by 0Shino0** [comment]
嗯，使用的是Hyperledger fabric 联盟链。但是我只是个小前端，更加具体的代码你可以去 https://github.com/AntonyCheng/share_study 看看。希望可以帮到你。

**Comment by 0Shino0** [comment]
如果没其他问题我将关闭Issues。
